### ISSUE TITLE
Cannot run locally with docker

### ISSUE THREAD

**Issue by ppalaga** [openshift-labs/starter-guides#96]
```
$ git remote -v
ppalaga git@github.com:ppalaga/starter-guides.git (fetch)
ppalaga git@github.com:ppalaga/starter-guides.git (push)
upstream        git@github.com:openshift-labs/starter-guides.git (fetch)
upstream        git@github.com:openshift-labs/starter-guides.git (push)

$ git fetch upstream
$ git checkout -b ocp-3.10 upstream/ocp-3.10
$ git log -1 --pretty=oneline
490e3330b446dda384b91f2a3b9a0589fa847bed (HEAD -> ocp-3.10, upstream/ocp-3.10) Updated guides-template
$ docker run -it --rm -p 8080:8080 -v $(pwd):/app-data \
              -e CONTENT_URL_PREFIX="file:///app-data" \
              -e LOG_TO_STDOUT=true \
              -e WORKSHOPS_URLS="file:///app-data/_workshops/java-starter-guides.yml" \
              quay.io/osevg/workshopper:latest
bundler: failed to load command: rackup (/workshopper/vendor/bundle/ruby/2.5.0/bin/rackup)
Errno::EACCES: Permission denied @ rb_sysopen - /app-data/_workshops/java-starter-guides.yml
  /workshopper/lib/workshopper/loader/file.rb:9:in `initialize'
  /workshopper/lib/workshopper/loader/file.rb:9:in `open'
  /workshopper/lib/workshopper/loader/file.rb:9:in `get'
  /workshopper/lib/workshopper/loader.rb:17:in `get'
  /workshopper/lib/workshopper/workshop.rb:13:in `initialize'
  /workshopper/lib/workshopper/cache.rb:12:in `new'
  /workshopper/lib/workshopper/cache.rb:12:in `add'
  /workshopper/config/initializers/workshopper.rb:8:in `block in <top (required)>'
  /workshopper/config/initializers/workshopper.rb:7:in `each'
  /workshopper/config/initializers/workshopper.rb:7:in `<top (required)>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:655:in `block in load_config_initializer'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:654:in `load_config_initializer'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
  /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
  /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
  /workshopper/config/environment.rb:5:in `<top (required)>'
  /workshopper/config.ru:3:in `require_relative'
  /workshopper/config.ru:3:in `block in <main>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  /workshopper/config.ru:in `new'
  /workshopper/config.ru:in `<main>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
  /workshopper/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `<top (required)>'

```

**Comment by ppalaga** [comment]
Any idea what I am doing wrong @marekjelen or @jorgemoralespou ?

**Comment by ppalaga** [comment]
I wonder why `/app-data/_workshops/java-starter-guides.yml` cannot be read. My whole clone is world readable.

Anyway, I was able to run with docker against the github repo:

```
docker run -it --rm -p 8080:8080 \
    -e CONTENT_URL_PREFIX="https://raw.githubusercontent.com/openshift-labs/starter-guides/ocp-3.10/" \
    -e LOG_TO_STDOUT=true \
    -e WORKSHOPS_URLS="https://raw.githubusercontent.com/openshift-labs/starter-guides/ocp-3.10/_workshops/java-starter-guides.yml" \
    quay.io/osevg/workshopper:latest
```

**Comment by jorgemoralespou** [comment]
There's an issue with selinux, until we fix it you can use :z or setenforce
0 temporarily.

>
